apiVersion: v1
kind: Service
metadata:
  name: coel-service
  labels:
    app: coel-devops-project
spec:
  selector:
    app: coel-devops-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31100
